name: Deploy a new API for each pull request

on:
  pull_request:
    branches: [ main ]
  
jobs:    
  deploy_api:
    uses: nguyenquyhy/Hy-Academy/.github/workflows/module-backend.yml@hy/pr-workflow-backend
    with:
      environment: Pull Requests
      containerAppName: hyacademypr${{ github.event.pull_request.number }}-api
    secrets:
      deploymentSpClientId: ${{ secrets.DEPLOYMENT_SERVICE_PRINCIPAL_CLIENT_ID }}
      deploymentSpTenantId: ${{ secrets.DEPLOYMENT_SERVICE_PRINCIPAL_TENANT_ID }}
      deploymentSpSubscriptionId: ${{ secrets.DEPLOYMENT_SERVICE_PRINCIPAL_SUBSCRIPTION_ID }}
      resourceGroupName: ${{ secrets.RESOURCE_GROUP_NAME }}
      containerEnvironmentName: ${{ secrets.CONTAINER_ENVIRONMENT_NAME }}
      dockerTag: docker.io/${{ secrets.DOCKER_TAG }}
      logAnalyticsSKU: ${{ secrets.LOG_ANALYTICS_SKU }}

  temp:
    runs-on: ubuntu-latest
    needs: [ deploy_api ]
    steps:
    - run: echo ${{ needs.deploy_api.outputs.apiDomain }}1