name: Deploy a new site for each pull request

on:
  pull_request:
    branches: [ main ]
env:
  PRNUMNER: 'academy${{github.event.pull_request.number}}'
  
permissions:
    id-token: write
    contents: read
  
jobs:
  Azure-Storage-Account:
     runs-on: ubuntu-latest
     environment: Pull Requests
     steps:
          - name: Azure Login
            uses: Azure/login@v1.4.2
            with: 
                client-id: ${{ secrets.DEPLOYMENT_SERVICE_PRINCIPAL_CLIENT_ID }}
                tenant-id: ${{ secrets.DEPLOYMENT_SERVICE_PRINCIPAL_TENANT_ID }}
                subscription-id: ${{ secrets.DEPLOYMENT_SERVICE_PRINCIPAL_SUBSCRIPTION_ID }}
          - name: Check Storage Account Exist
            id: checkAccountExist
            uses: azure/CLI@1.0.4
            with:
              inlineScript: |
                  echo "::set-output name=isNew::`az storage account check-name --name ${PRNUMNER} --query nameAvailable`"

          - name: Create Storage Account
            if: ${{ steps.checkAccountExist.outputs.isNew == 'true'}}
            uses: azure/CLI@1.0.4
            with:
              inlineScript: |
                  az storage account create -n ${PRNUMNER} -g '${{ secrets.RESOURCE_GROUP_NAME }}' -l SoutheastAsia --sku Standard_LRS --kind StorageV2
                  
          - name: Enable Static Site
            if: ${{ steps.checkAccount.outputs.isNew == 'true'}}
            uses: azure/CLI@1.0.4
            with:
              inlineScript: |
                  az storage blob service-properties update --account-name ${PRNUMNER} --static-website --404-document index.html --index-document index.html
          
          
          - name: Azure logout
            run: |
                  az logout
            if: always()
