name: CI-CD Frontend

on:
  # Triggers the workflow on push request events but only for the main branch
  push:
    branches: [ main ]
    paths: 'React/**'
  pull_request:
      branches: [ main ]  
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-test-archive:  
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Install NPM packages
        working-directory: ./React
        run: npm ci

      - name: Run lint
        working-directory: ./React
        run: npm run lint
      
      - name: Run build
        working-directory: ./React
        run: npm run build
          
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: package-deployment
          path: ./React/build

  deploy:
    runs-on: ubuntu-latest
    needs: [build-test-archive]
    steps:
      - name: Download artifacts
        env:
          tenant-id: ${{ env.DEPLOYMENT_SERVICE_PRINCIPAL_TENANT_ID }}
          client-id: ${{ env.DEPLOYMENT_SERVICE_PRINCIPAL_CLIENT_ID }}
          subscription-id: ${{ env.DEPLOYMENT_SERVICE_PRINCIPAL_SUBSCRIPTION_ID }}
          cre: ${{ secrets.DEPLOYMENT_SERVICE_PRINCIPAL_CREDENTIALS }}
        uses: actions/download-artifact@v2
        with:
          name: package-deployment
          path: ./build
          
      - name: azure login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.DEPLOYMENT_SERVICE_PRINCIPAL_CLIENT_ID }}
          tenant-id: ${{ secrets.DEPLOYMENT_SERVICE_PRINCIPAL_TENANT_ID }}
          subscription-id: ${{ secrets.DEPLOYMENT_SERVICE_PRINCIPAL_SUBSCRIPTION_ID }}
          
      - name: Upload to Storage Account
        uses: azure/CLI@1.0.4
        with:
          azcliversion: 2.0.72
          inlineScript: |
            az storage blob upload-batch --account-name '${{ env.REACT_STORAGE_ACCOUNT_NAME }}' --auth-mode key -s './build' -d '$web'
            
      - name: azure logout
        run: |
              az logout
        if: always()
