name: Delete webapp and API when pull request is closed or merged

on:
  pull_request:
    branches: [ main ]
    types: [closed, locked]
  
jobs:
  cleanup_app:
    uses: nguyenquyhy/Hy-Academy/.github/workflows/module-frontend-cleanup.yml@hy/pr-workflow-backend
    with:
      environment: Pull Requests
      storageAccountName: hyacademypr${{ github.event.pull_request.number }}
    secrets:
      deploymentSpClientId: ${{ secrets.DEPLOYMENT_SERVICE_PRINCIPAL_CLIENT_ID }}
      deploymentSpTenantId: ${{ secrets.DEPLOYMENT_SERVICE_PRINCIPAL_TENANT_ID }}
      deploymentSpSubscriptionId: ${{ secrets.DEPLOYMENT_SERVICE_PRINCIPAL_SUBSCRIPTION_ID }}
      resourceGroupName: ${{ secrets.RESOURCE_GROUP_NAME }}
