name: CI-CD Frontend

on:
  # Triggers the workflow on push request events but only for the main branch
  push:
    branches: [ main ]
    paths: 'React/**'
  pull_request:
      branches: [ main ]  
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        env:
          TEST_CLIENTID: ${{ secrets.DEPLOYMENT_SERVICE_PRINCIPAL_CLIENT_ID }}
        run: |
          echo ${#TEST_CLIENTID}
          
      - name: 'Az CLI login'
        uses: azure/login@v1.4.2
        with:
          client-id: ${{ secrets.DEPLOYMENT_SERVICE_PRINCIPAL_CLIENT_ID }}
          tenant-id: ${{ secrets.DEPLOYMENT_SERVICE_PRINCIPAL_TENANT_ID }}
          subscription-id: ${{ secrets.DEPLOYMENT_SERVICE_PRINCIPAL_SUBSCRIPTION_ID }}
        env:
          client-id: ${{ secrets.DEPLOYMENT_SERVICE_PRINCIPAL_CLIENT_ID }}
          tenant-id: ${{ secrets.DEPLOYMENT_SERVICE_PRINCIPAL_TENANT_ID }}
          subscription-id: ${{ secrets.DEPLOYMENT_SERVICE_PRINCIPAL_SUBSCRIPTION_ID }}
          creds: ${{ secrets.DEPLOYMENT_SERVICE_PRINCIPAL_CREDENTIALS }}
          cred: ${{ secrets.DEPLOYMENT_SERVICE_PRINCIPAL_CREDENTIAL }}
          react: ${{ env.REACT_STORAGE_ACCOUNT_NAME }}
      - name: azure logout
        run: |
              az logout
        if: always()
