name: Delete webapp and API when pull request is closed or merged

on:
  pull_request:
    branches: [ main ]
    types: [closed, locked]
  
jobs:
  cleanup_app:
    uses: nguyenquyhy/Hy-Academy/.github/workflows/module-frontend-cleanup.yml@main
    with:
      environment: Pull Requests
      storageAccountName: hyacademypr${{ github.event.pull_request.number }}
    secrets:
      deploymentSpClientId: ${{ secrets.DEPLOYMENT_SERVICE_PRINCIPAL_CLIENT_ID }}
      deploymentSpTenantId: ${{ secrets.DEPLOYMENT_SERVICE_PRINCIPAL_TENANT_ID }}
      deploymentSpSubscriptionId: ${{ secrets.DEPLOYMENT_SERVICE_PRINCIPAL_SUBSCRIPTION_ID }}
      resourceGroupName: ${{ secrets.RESOURCE_GROUP_NAME }}
      
  cleanup_api:
    uses: nguyenquyhy/Hy-Academy/.github/workflows/module-backend-cleanup.yml@hy/fix-action-close-pr
    with:
      environment: Pull Requests
      containerAppName: hyacademypr${{ github.event.pull_request.number }}-api
      dockerTag: pr${{ github.event.pull_request.number }}
    secrets:
      deploymentSpClientId: ${{ secrets.DEPLOYMENT_SERVICE_PRINCIPAL_CLIENT_ID }}
      deploymentSpTenantId: ${{ secrets.DEPLOYMENT_SERVICE_PRINCIPAL_TENANT_ID }}
      deploymentSpSubscriptionId: ${{ secrets.DEPLOYMENT_SERVICE_PRINCIPAL_SUBSCRIPTION_ID }}
      resourceGroupName: ${{ secrets.RESOURCE_GROUP_NAME }}
      dockerUsername: ${{ secrets.DOCKER_USERNAME }}
      dockerPassword: ${{ secrets.DOCKER_PASSWORD }}
      dockerImage: ${{ secrets.DOCKER_IMAGE }}
