name: Deploy a new API for each pull request

on:
  pull_request:
    branches: [ main ]
env:
  PRNUMNER: 'hyacademypr${{github.event.pull_request.number}}'  
  
jobs:    
  deploy_api:
    uses: nguyenquyhy/Hy-Academy/.github/workflows/module-backend.yml
    with:
      environment: Pull Requests
    secrets:
      resourceGroupName: ${{ secrets.RESOURCE_GROUP_NAME }}
      containerAppName: ${{ env.PRNUMNER }}-api
      containerEnvironmentName: ${{ secrets.CONTAINER_ENVIRONMENT_NAME }}
      dockerTag: docker.io/${{ secrets.DOCKER_TAG }}
      logAnalyticsSKU: ${{ secrets.LOG_ANALYTICS_SKU }}

  temp:
    runs-on: ubuntu-latest
    steps:
    - run: echo ${{ needs.deploy_api.outputs.apiDomain }}