name: CI-CD Frontend

on:
  # Triggers the workflow on push request events but only for the main branch
  push:
    branches: [ main ]
    paths: 'React/**'  
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions: 
  id-token: write
  contents: read
jobs:
  build-test-archive:  
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Install NPM packages
        working-directory: ./React
        run: npm ci

      - name: Run lint
        working-directory: ./React
        run: npm run lint
      
      - name: Run build
        working-directory: ./React
        run: npm run build
          
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: package-deployment
          path: ./React/build

  create-resource:
    runs-on: ubuntu-latest
    environment: Production
    steps: 
      - name: Check out repository
        uses: actions/checkout@v2
        
      - name: Azure login
        uses: azure/login@v1.4.2
        with:
          client-id: ${{ secrets.DEPLOYMENT_SERVICE_PRINCIPAL_CLIENT_ID }}
          tenant-id: ${{ secrets.DEPLOYMENT_SERVICE_PRINCIPAL_TENANT_ID }}
          subscription-id: ${{ secrets.DEPLOYMENT_SERVICE_PRINCIPAL_SUBSCRIPTION_ID }}
          
      - name: Create Azure resources
        uses: azure/arm-deploy@v1
        with:
          resourceGroupName: ${{ secrets.RESOURCE_GROUP_NAME }}
          template: ./.azure/frontend.bicep
          parameters: storageAccountName=${{ secrets.REACT_STORAGE_ACCOUNT_NAME }}
      
      - name: Azure logout
        run: |
              az logout
        if: always()
      
  deploy:
    runs-on: ubuntu-latest	  
    needs: [build-test-archive, create-resource]
    environment: Production
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: package-deployment
          path: ./build
          
      - name: Azure login
        uses: azure/login@v1.4.2
        with:
          client-id: ${{ secrets.DEPLOYMENT_SERVICE_PRINCIPAL_CLIENT_ID }}
          tenant-id: ${{ secrets.DEPLOYMENT_SERVICE_PRINCIPAL_TENANT_ID }}
          subscription-id: ${{ secrets.DEPLOYMENT_SERVICE_PRINCIPAL_SUBSCRIPTION_ID }}
          
      - name: Upload to Storage Account
        uses: azure/CLI@1.0.4
        with:
          azcliversion: 2.30.0
          inlineScript: |
            az storage blob upload-batch --subscription '${{ secrets.DEPLOYMENT_SERVICE_PRINCIPAL_SUBSCRIPTION_ID }}'  --account-name '${{ secrets.REACT_STORAGE_ACCOUNT_NAME }}' --auth-mode key -s './build' -d 'web'
            
      - name: Azure logout
        run: |
              az logout
        if: always()
