name: CI-CD Frontend

on:
  # Triggers the workflow on push request events but only for the main branch
  push:
    branches: [ main ]
    paths: 'React/**'
  pull_request:
      branches: [ main ]  
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Production
    steps:          
      - name: 'Az CLI login'
        uses: azure/login@v1.4.2
        with:
          creds: ${{ secrets.DEPLOYMENT_SERVICE_PRINCIPAL_CREDENTIALS }}
        
      - name: azure logout
        run: |
              az logout
        if: always()
