name: Deploy frontend

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      backendUrl:
        required: true
        type: string
    secrets:
      deploymentSpClientId:
        required: true
      deploymentSpTenantId:
        required: true
      deploymentSpSubscriptionId:
        required: true

jobs:
  build_react_package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Install NPM packages
        working-directory: ./React
        run: npm ci
      
      - name: Run Build
        working-directory: ./React
        run: |
          export REACT_APP_API_URL=${{ inputs.backendUrl }}
          npm run build
          
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: package-deployment
          path: ./React/build
          
  deploy_app:
    runs-on: ubuntu-latest
    needs: [build_react_package]
    environment: ${{ inputs.environment }}
    permissions:
      id-token: write
      contents: read
    
    steps:      
      - uses: actions/download-artifact@v2
        with:
          name: package-deployment
          path: ./build
          
      - name: Azure Login
        uses: Azure/login@v1.4.2
        with:
          client-id: ${{ secrets.deploymentSpClientId }}
          tenant-id: ${{ secrets.deploymentSpTenantId }}
          subscription-id: ${{ secrets.deploymentSpSubscriptionId }}       
          
      - name: Upload to blob storage
        uses: azure/CLI@1.0.4
        with:
          inlineScript: |
            az storage blob upload-batch --subscription '${{ secrets.DEPLOYMENT_SERVICE_PRINCIPAL_SUBSCRIPTION_ID }}' --account-name ${PRNUMNER} --auth-mode key -s './build' -d '$web'
            
      - name: Azure logout
        run: |
            az logout
        if: always()