name: Delete resources of backend

on:
  pull_request:
    branches: [main]

jobs:
  delete_dockerhub_tag:
    runs-on: ubuntu-latest
    environment: Pull Requests
    steps:
      - name: Delete tag
        run: |
          TOKEN=$(curl -s -H "Content-Type: application/json" -X POST -d "{\"username\":\"${{ secrets.DOCKER_USERNAME }}\",\"password\":\"${{ secrets.DOCKER_PASSWORD }}\"}" "https://hub.docker.com/v2/users/login/" | jq -r .token)
          echo ${TOKEN}
          curl "https://hub.docker.com/v2/repositories/${{ secrets.DOCKER_IMAGE }}/tags/pr${{ inputs.github.event.pull_request.number }}/" -X DELETE -H "Authorization: Bearer ${TOKEN}"
